### ISSUE TITLE
CLI mode docs missing details

### ISSUE THREAD

**Issue by cameronelliott** [Granulate/gprofiler#297] opened 2022-02-15 22:45 UTC
I wanted to try gprofiler.
Setup an account.
Looked at the CLI docs.
The CLI docs don't appear to explain which processes will be profiled, and how that set is determined.
Don't feel good about using a profiler that doesn't explain that.

**Comment by Jongy** [comment] 2022-02-15 23:05
Hi! Thanks for wanting to try out the profiler :) 

gProfiler is a system-wide profiler: by design, it profiles all processes running on the system, and  westrive to provide you with useful and easy-to-use filters & aggregations when viewing the result profiles.

The [main README section](https://github.com/Granulate/gprofiler#gprofiler) starts with:

> gProfiler combines multiple sampling profilers to produce unified visualization of what your CPU is spending time on, displaying stack traces of your processes across native programs (includes Golang), Java and Python runtimes, and kernel routines.

Would it be more clear had we specifically mentioned that all processes are more profiled here? Something like:

> gProfiler combines multiple sampling profilers to produce unified visualization of what your CPU is spending time on, displaying stack traces of all processes running on your system, across native programs (includes Golang), Java and Python runtimes, and kernel routines.

Likewise - we can add a similar section to the CLI `gprofiler -h` output, so it'd be more clear when trying out the CLI without referring to the docs.

**Comment by Jongy** [comment] 2022-11-19 01:29
I clarified things up in https://github.com/Granulate/gprofiler/pull/608.

**Comment by Jongy** [comment] 2022-11-21 14:22
Closing it as the documentation I found relevant was added and it's now clear in the `-h` where the docs are present. Let me know if you think any additions are fit.

**Closed by Jongy** 2022-11-21 14:22 UTC
Labels: question
